name: Compile dissertation

on:
  pull_request:
    branches: [master, development]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file:
              dissertation/l4proj.tex
#         uses: vinay0410/tectonic-action@v1.1.2
#         with:
#           # Path of Tex File:
#           tex_path: dissertation/l4proj.tex
#           # String stating whether to push output PDF, PDF will only be pushed in case of "yes"
#           push: no # optional, default is no
