name: Django CI

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master, development]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          cd seminar-roulette
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          cd seminar-roulette
          python manage.py test
