name: Node.js CI

on:
  pull_request:
    brances: [master, development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - run: npm run dev
      - run: npm test
