# Generated by Django 3.1.2 on 2020-10-20 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='universityuser',
            name='is_staff',
        ),
    ]
