# Generated by Django 3.1.2 on 2020-10-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201020_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='universityuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
