# Generated by Django 3.1.2 on 2020-10-22 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201022_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminargroup',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=50)),
                ('affiliation', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('speaker', 'affiliation')},
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('registration_url', models.URLField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('seminar_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.seminargroup')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.speaker')),
            ],
            options={
                'unique_together': {('title', 'start_time', 'end_time', 'speaker')},
            },
        ),
    ]
