# Generated by Django 3.1.2 on 2020-10-22 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201022_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='seminar_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.seminargroup'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.speaker'),
        ),
        migrations.AlterField(
            model_name='seminargroup',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.location'),
        ),
    ]
