# Generated by Django 3.1.2 on 2020-10-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201022_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
