# Generated by Django 3.1.2 on 2020-10-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201022_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='registration_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seminargroup',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='speaker',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
