# Generated by Django 3.1.2 on 2020-10-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201022_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.location'),
        ),
    ]
