# Generated by Django 3.1.2 on 2020-10-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_seminar_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.location'),
        ),
    ]
