# Generated by Django 3.1.2 on 2020-10-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20201022_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('location', 'latitude', 'longitude')},
        ),
    ]
