# Generated by Django 3.1.2 on 2020-10-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20201022_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='samoa_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
