# Generated by Django 3.1.2 on 2020-10-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_seminar_samoa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
