# Generated by Django 3.1.2 on 2020-10-26 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20201026_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.speaker'),
        ),
    ]
