# Generated by Django 3.1.2 on 2020-10-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20201029_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminarhistory',
            options={'verbose_name_plural': 'seminar histories'},
        ),
        migrations.RemoveConstraint(
            model_name='seminarhistory',
            name='Rating must be between 1 and 10',
        ),
    ]
