# Generated by Django 3.1.2 on 2020-11-04 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20201029_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarhistory',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
