# Generated by Django 3.1.2 on 2020-11-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20201104_2122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seminar',
            unique_together={('title', 'start_time', 'end_time', 'speaker', 'samoa_id')},
        ),
    ]
