# Generated by Django 3.1.2 on 2020-11-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20201105_1812'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seminargroup',
            unique_together={('name', 'short_name')},
        ),
    ]
