# Generated by Django 3.1.2 on 2020-11-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_seminar_eventbrite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='eventbrite_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
