# Generated by Django 3.1.2 on 2020-11-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20201118_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
