# Generated by Django 3.1.2 on 2020-12-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_seminar_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityuser',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
