# Generated by Django 3.1.2 on 2020-12-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_universityuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityuser',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
