# Generated by Django 3.1.2 on 2020-12-07 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_remove_universityuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityuser',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
