# Generated by Django 3.1.2 on 2020-12-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_universityuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
