# Generated by Django 3.1.2 on 2021-01-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_cronjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminargroup',
            name='samoa_group_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
