# Generated by Django 3.1.2 on 2021-01-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_seminargroup_samoa_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='icalendar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
