# Generated by Django 3.1.2 on 2021-01-11 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_seminar_icalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityuser',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
    ]
