# Generated by Django 3.1.2 on 2021-01-11 15:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_universityuser_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityuser',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=5),
        ),
    ]
