# Generated by Django 3.1.2 on 2021-01-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_auto_20210111_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
