# Generated by Django 3.1.2 on 2021-01-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_seminar_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='similarities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
