# Generated by Django 3.1.2 on 2021-01-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_seminar_similarities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='similarities',
        ),
    ]
