# Generated by Django 3.1.2 on 2021-01-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_seminar_serves_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityuser',
            name='dark_theme_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
